ProductCategoryScreen1 As screen:
    LoadingSpinnerColor: =RGBA(105, 121, 126, 1)

    RectQuickActionBar_WO_1 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 0)
        Fill: =RGBA(105, 121, 126, 1)
        Height: =88
        Width: =Parent.Width
        Y: =1
        ZIndex: =18

    IconBackarrow1_7 As icon.ChevronLeft:
        AccessibleLabel: =Self.Tooltip
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        Height: =88
        Icon: =Icon.ChevronLeft
        OnSelect: =Back()
        PaddingBottom: =24
        PaddingLeft: =24
        PaddingRight: =24
        PaddingTop: =24
        PressedFill: =RGBA(0, 0, 0, 0)
        TabIndex: =0
        Tooltip: ="목록으로 돌아가기"
        Width: =88
        Y: =1
        ZIndex: =19

    LblAppName2_2 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.'Segoe UI'
        Height: =88
        Size: =25
        Text: ="Product Category"
        Width: |
            =Parent.Width - Self.X - IconBackarrow1_7.Width
        Wrap: =false
        X: =80
        Y: =1
        ZIndex: =20

    Container4 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Light
        Height: =225
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =App.Width
        Y: =RectQuickActionBar_WO_1.Height
        ZIndex: =27

        Label7_2 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            Color: =RGBA(139, 154, 159, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =50
            Italic: =true
            Size: =gblFontSize
            Text: ="Standard ESS (2C6R)"
            Width: =App.Width - 60
            X: =10
            Y: =10
            ZIndex: =1

        btn_ess_bpu As 버튼:
            BasePaletteColor: =RGBA(141, 229, 250, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            OnSelect: |-
                =Navigate(RegisterScreen_BPU,ScreenTransition.Fade);
                Set(varProductType, "BPU")
            Text: ="BPUs"
            Width: =158
            X: =btn_ess_bcp.X - Self.Width - 40
            Y: =(Parent.Height + Label7_2.Height- Self.Height) * 0.5
            ZIndex: =2

        btn_ess_bcp As 버튼:
            Appearance: ='ButtonCanvas.Appearance'.Primary
            BasePaletteColor: =RGBA(189, 178, 176, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            IconStyle: ='ButtonCanvas.IconStyle'.Outline
            Text: ="BCPs"
            Width: =158
            X: =(Parent.Width - Self.Width) * 0.5
            Y: =(Parent.Height + Label7_2.Height- Self.Height) * 0.5
            ZIndex: =3

        btn_ess_rack As 버튼:
            BasePaletteColor: =RGBA(189, 178, 176, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            Text: ="RACKs"
            Width: =158
            X: =btn_ess_bcp.X + Self.Width + 40
            Y: =(Parent.Height + Label7_2.Height- Self.Height) * 0.5
            ZIndex: =4

    Container4_1 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Light
        Height: =225
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =App.Width
        Y: =Container4.Y + Container4.Height
        ZIndex: =28

        Label7_3 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            Color: =RGBA(139, 154, 159, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =50
            Italic: =true
            Size: =gblFontSize
            Text: ="UPS (1C4R, 1C5R)"
            Width: =App.Width - 60
            X: =10
            Y: =10
            ZIndex: =1

        btn_ess_bpu_1 As 버튼:
            BasePaletteColor: =RGBA(189, 178, 176, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            Text: ="BPUs"
            Width: =158
            X: =btn_ess_bcp_1.X - Self.Width - 40
            Y: =(Parent.Height + Label7_3.Height- Self.Height) * 0.5
            ZIndex: =2

        btn_ess_bcp_1 As 버튼:
            Appearance: ='ButtonCanvas.Appearance'.Primary
            BasePaletteColor: =RGBA(141, 229, 250, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            IconStyle: ='ButtonCanvas.IconStyle'.Outline
            OnSelect: |-
                =Navigate(RegisterScreen_BCP,ScreenTransition.Fade);
                Set(varProductType, "BCP")
            Text: ="BCPs"
            Width: =158
            X: =(Parent.Width - Self.Width) * 0.5
            Y: =(Parent.Height + Label7_3.Height- Self.Height) * 0.5
            ZIndex: =3

        btn_ess_rack_1 As 버튼:
            BasePaletteColor: =RGBA(189, 178, 176, 1)
            BorderColor: =
            BorderStyle: =""
            DisplayMode: =DisplayMode.Edit
            FontColor: =
            FontSize: =gblFontSize
            Height: =74
            Text: ="RACKs"
            Width: =158
            X: =btn_ess_bcp_1.X + Self.Width + 40
            Y: =(Parent.Height + Label7_3.Height- Self.Height) * 0.5
            ZIndex: =4

    nav_bar_3 As nav_bar:
        browseScreen: =BrowseScreen1
        homeScreen: =MainScreen1
        inspectScreen: =InspectScreen1
        registerScreen: =ProductCategoryScreen1
        supportScreen: =SupportScreen1
        userPermission: |-
            =LookUp ('[MR01]app_userpermissions',
                    User_Email = User().Email, Permission_Level)
        Y: =App.Height - Self.Height
        ZIndex: =29

